### ISSUE TITLE
Automatic sending of crash logs to bugzilla

### ISSUE THREAD

**Issue by gnu-user** [tinfoilhat/tinfoil-sms#10]
This has already been looked into several months ago and there are libraries which already exist to facilitate this. Support should be added to automatically send **unique** detailed crash logs to bugzilla.

As well, we should also look into adding an activity to add support (perhaps in the main menu) for users to submit their own bug reports / issues.

**Comment by dataBaseError** [comment]
Decided on using acra instead of bugzilla.

Acra has been implemented in 56ab85fd77432ab894ffb0b4975eaab75112b586 and is currently able to be turned off if desired by the user.
