### ISSUE TITLE
Clicking on Notifications causes program to crash

### ISSUE THREAD

**Issue by dataBaseError** [tinfoilhat/tinfoil-sms#12]
When a user receives a message from a contact the notification for that message will appear in the notifications bar. If the user clicks on the notification to take them to the contact's list of messages the program will proceed to MessageView activity but crash once there.

**Comment by dataBaseError** [comment]
This issue could not be recreated after updating to the latest version.

**Comment by gnu-user** [comment]
@dataBaseError This is the error I was having earlier that I told you about where it kept crashing, I'll do a git pull now and test.
