### ISSUE TITLE
Dropping Supprot for Android 2.2

### ISSUE THREAD

**Issue by gnu-user** [tinfoilhat/tinfoil-sms#13]
## Proposal

Dropping support for Android 2.2, not because I don't want to support Android 2.2 devices, but primarily because Android 2.2 only support **Java 1.5!**. Supporting Android 2.2 makes it very difficult for me to use external libraries, as all of them require at least Java 1.6, as well there are some nice enhancements in Java 1.6 that I would like to use in coding.
## Solution

Leave things the way they are for now, however I am running into issues trying to get the auto-bug reporting to work since some libraries require 1.6. As well I would like to use a newer version of BouncyCastle (java 1.6 required) in the future.

**Comment by dataBaseError** [comment]
Tinfoil-SMS only supports 2.3 and above.
