### ISSUE TITLE
Encryption.isKeyExchange returns true for plain text messages

### ISSUE THREAD

**Issue by dataBaseError** [tinfoilhat/tinfoil-sms#5]
isKeyExchange is returning true when plain text messages are sent between users.

To repeat:
- Set two contacts to not trusted state
- Send a message from 1 contact to the other.
- The receiving contact's app will crash, (because of a bug in Encryption.verify but verify is within an if structure that has the condition that Encryption.isKeyExchange, of the message, must be true)

**Comment by gnu-user** [comment]
This has now been fixed, I attempted to initially use a unique encoding for key exchanges, Ascii85, but found out that sending Ascii85 encoded messages were being corrupted by the SMS protocol perhaps? 

The solution was to use an additional CRC32 checksum for the key exchange, this can be used to quickly check any incoming message from non trusted contacts (where a key exchange has not occurred yet), to determine if the message is a key exchange message.

SEE: fca140bd29f4921b0b01bc357463b08ce63f6cb7 for more details.
