### ISSUE TITLE
Encryption.verify is throwing a fatal exception 

### ISSUE THREAD

**Issue by dataBaseError** [tinfoilhat/tinfoil-sms#6]
Encryption.verify is crashing tinfoil-sms if a plain text message passed to it.
While this method should only really be used on known key exchange messages it is the method checking if the key exchange is a valid key exchange, in the sense that it is actually a key exchange as well as that it is the key exchange that is valid based on the shared secrets known by the user (and the contact).

**Comment by gnu-user** [comment]
The issue has been resolved in f6a8811e59296a359fcb99e869fa266f38960ed2, the method now throws a DataLengthException (which can be properly handled), if the signed public key to verify is smaller than the size of the signature.
