### ISSUE TITLE
If a message fails to send the nonces will get corrupted

### ISSUE THREAD

**Issue by gnu-user** [tinfoilhat/tinfoil-sms#8]
## Issue

If a message ever fails to send the nonce numbering will get corrupted, which results in a cascading failure, as all future messages **encrypted/decrypted will fail**.

For example, a malicious person (mallory) could easily make it so that both users can no longer properly send encrypted messages by simply blocking/dropping one of the messages. This would corrupt the nonce counters and result in all future messages being encrypted/decrypted improperly.
## Proposed Solution

Encode the nonce cycle count at the start of the each message as a 2 byte unsigned number (or whatever the Nonce.MAX_CYCLES value is, which should be 65,353) then proceed to encrypt the entire message. At which point if two users go over the limit they would need to regenerate their nonces/re-exchange new keys anyways because they have exceeded the Nonce.MAX_CYCLES value.

**Comment by gnu-user** [comment]
Impossible to implement the way I had planned since the receiving user cannot decrypt the message to get the nonce value. The only solution I can see is to add the unencrypted nonce to the encrypted message, however this is not an optimal solution.

**Comment by dataBaseError** [comment]
I though of two possible solutions:
1. If a user receives a message and it fails, the nonce count could be increased and tried again for a few times until the correct count is found. (A further precaution could be that at least 1 successful encrypted message was sent between the user and the contact).
2. This is less of a solution but does this really happen that often? Depending on the rarity of this event I might suggest just doing nothing, or doing my first purposed solution. Even though increasing the count and trying again isn't ideal if it was only once every 10 years for a contact and this successfully works in finding the correct nonce to use does it really matter?

**Comment by gnu-user** [comment]
The proposed solution has been implemented in **15c81beb0ec745d0d1d7c7765f316c60c6e4c09f**, the nonce is sent unencrypted and is prefixed to the beginning of the encrypted message. This helps prevent a cascading issues where no future messages can be decrypted by the recipient if the nonce counter is corrupted due to a message not being successfully sent and received.

For each user there is a threshold for how much the nonce counter received with the message can deviate from the local nonce counter the user has for the contact. This prevents an attack where an adversary can exhaust the number of nonces by sending the maximum nonce value.
